# Generated by Django 2.0.1 on 2018-01-22 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ser_social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('matricule', models.IntegerField(primary_key=True, serialize=False)),
                ('cnam', models.IntegerField()),
                ('nom_prenom', models.CharField(max_length=100)),
                ('date_emb', models.DateTimeField()),
                ('date_dep', models.DateTimeField()),
                ('statut', models.CharField(max_length=10)),
                ('civilite', models.CharField(default='Homme', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Gains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('montant', models.IntegerField(null=True)),
                ('libele_g', models.TextField(null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Employe')),
            ],
        ),
        migrations.CreateModel(
            name='InfoEmploye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('somme', models.IntegerField()),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Employe')),
                ('pelerin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ser_social.Pelerinage')),
            ],
        ),
    ]
