# Generated by Django 2.0.1 on 2018-01-22 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_en', models.DateField()),
                ('montant', models.IntegerField(null=True)),
                ('motif', models.TextField(null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Employe')),
            ],
        ),
        migrations.CreateModel(
            name='TypeEng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='engagement',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ser_retraite.TypeEng'),
        ),
    ]
