# Generated by Django 2.0.1 on 2018-01-22 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AyDroits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=30)),
                ('statut', models.CharField(max_length=10)),
                ('date_de_naiss', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Clinique',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('libele', models.CharField(max_length=20)),
                ('pays', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('', '----------------'), ('Local', 'Local'), ('Etranger', 'Etranger')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Droits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rec', models.DateTimeField()),
                ('montant', models.IntegerField(null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Employe')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnances',
            fields=[
                ('reference', models.IntegerField(primary_key=True, serialize=False)),
                ('date_soum', models.DateTimeField(auto_now=True)),
                ('montant', models.IntegerField(null=True)),
                ('montant_rem', models.IntegerField()),
                ('type', models.CharField(choices=[('', '----------------'), ('0', 'Lunette'), ('1', 'Dent')], max_length=20)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Employe')),
            ],
        ),
        migrations.CreateModel(
            name='PieceComptable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emetteur', models.CharField(choices=[('', '----------------'), ('Service Action Sociale', 'Service Action Sociale'), ('Service Medical', 'Service Medical'), ('Service Retraite', 'Service Retraite')], max_length=100)),
                ('objet', models.CharField(max_length=100)),
                ('date_p', models.DateTimeField(auto_now=True)),
                ('compte', models.IntegerField()),
                ('intitule', models.TextField()),
                ('libele', models.TextField()),
                ('montant', models.IntegerField()),
                ('sens', models.CharField(choices=[('', '----------------'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Employe')),
            ],
        ),
        migrations.CreateModel(
            name='Soins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_prenom', models.CharField(max_length=100)),
                ('id_patient', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('date_soin', models.DateTimeField(auto_now=True)),
                ('chef_sec', models.CharField(choices=[('', '----------------'), ('defavorable', 'defavorable'), ('favorable', 'favorable')], max_length=100, null=True)),
                ('chef_serv', models.CharField(choices=[('', '----------------'), ('defavorable', 'defavorable'), ('favorable', 'favorable')], max_length=100, null=True)),
                ('dir', models.CharField(choices=[('', '----------------'), ('defavorable', 'defavorable'), ('favorable', 'favorable')], max_length=100, null=True)),
                ('Matricule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Employe')),
                ('clinique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ser_medical.Clinique')),
            ],
        ),
        migrations.CreateModel(
            name='TypeClinique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDroit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeSoins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='droits',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ser_medical.TypeDroit'),
        ),
    ]
